# Generated by Django 5.1.3 on 2026-05-16 09:07

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('L', 'Logopeda'), ('F', 'Familiar')], default='F', max_length=1)),
                ('foto_usuario', models.ImageField(blank=True, null=True, upload_to='imagenes/foto_usuario/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_paciente', models.ImageField(blank=True, null=True, upload_to='imagenes/foto_paciente/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('familiar', models.ForeignKey(limit_choices_to={'rol': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='familiar_registrado', to=settings.AUTH_USER_MODEL)),
                ('logopeda_asignado', models.ForeignKey(limit_choices_to={'rol': 'L'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion_Periodica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('areas', models.TextField(blank=True, null=True)),
                ('instrumentos', models.CharField(max_length=225)),
                ('cambios', models.TextField(blank=True, null=True)),
                ('puntuacion', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='app_daehwa.paciente')),
            ],
            options={
                'verbose_name': 'Evaluacion_Inicial',
                'verbose_name_plural': 'Evaluacion_Periodica',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion_Inicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_clinicos', models.TextField(blank=True, null=True)),
                ('entorno_familiar', models.TextField(blank=True, null=True)),
                ('pruebas', models.TextField(blank=True, null=True)),
                ('archivos_adjuntos', models.FileField(blank=True, null=True, upload_to='archivos/evaluacion_inicial/')),
                ('observacion_directa', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_inicial', to='app_daehwa.paciente')),
            ],
            options={
                'verbose_name': 'Evaluacion_Inicial',
                'verbose_name_plural': 'Evaluacion_Inicial',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico_Funcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diagnostico_funcional', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico_funcional', to='app_daehwa.paciente')),
            ],
            options={
                'verbose_name': 'Diagnostico_Funcional',
                'verbose_name_plural': 'Diagnostico_Funcional',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('id_usuario_logopeda', models.ForeignKey(limit_choices_to={'rol': 'L'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_logopeda', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app_daehwa.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Plan_Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_especificos', models.TextField()),
                ('contenidos', models.TextField()),
                ('frecuencia', models.IntegerField()),
                ('duracion_sesiones', models.IntegerField()),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_intervencion', to='app_daehwa.paciente')),
            ],
            options={
                'verbose_name': 'Plan_Intervencion',
                'verbose_name_plural': 'Plan_Intervencion',
            },
        ),
        migrations.CreateModel(
            name='Registro_Sesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividades', models.TextField()),
                ('areas_lenguaje', models.CharField(max_length=225)),
                ('logros', models.TextField(blank=True, null=True)),
                ('aspectos_mejorar', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='archivos/registro_sesiones/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='app_daehwa.paciente')),
            ],
            options={
                'verbose_name': 'Registro_Sesion',
                'verbose_name_plural': 'Registro_Sesiones',
            },
        ),
    ]
