# Generated by Django 5.1.3 on 2026-05-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_daehwa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico_funcional',
            options={'verbose_name': 'Diagnostico Funcional', 'verbose_name_plural': 'Diagnostico Funcional'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion_inicial',
            options={'verbose_name': 'Evaluacion Inicial', 'verbose_name_plural': 'Evaluacion Inicial'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion_periodica',
            options={'verbose_name': 'Evaluacion Periodica', 'verbose_name_plural': 'Evaluacion Periodica'},
        ),
        migrations.AlterModelOptions(
            name='plan_intervencion',
            options={'verbose_name': 'Plan Intervencion', 'verbose_name_plural': 'Plan Intervencion'},
        ),
        migrations.AlterModelOptions(
            name='registro_sesiones',
            options={'verbose_name': 'Registro Sesion', 'verbose_name_plural': 'Registro Sesiones'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='foto_paciente',
        ),
    ]
